name: clean_architecture_tdd_course
description: TDD Clean Architecture for Flutter

version: 1.0.0+1

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Service locator
  get_it: ^3.1.0
  # Bloc for state management
  flutter_bloc: ^3.0.0
  # Value equality
  equatable: ^1.0.1
  # Functional programming thingies
  dartz: ^0.8.9
  # Remote API
  data_connection_checker: ^0.3.4
  http: ^0.12.0+3
  # Local cache
  shared_preferences: ^0.5.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1

flutter:
  uses-material-design: true
